### ISSUE TITLE
[Bug] Cannot Copy Paste

### ISSUE THREAD

**Issue by jack-at-circle** [mysql/mysql-shell-plugins#43] opened 2024-01-11 01:00 UTC
I just installed on Mac OS and can't copy paste hostnames, passwords, etc in the dialogues to setup a new connection. 

This makes it annoying to configure the 100 or so db connections I would have to set up if I were to use this tool.

**Comment by mike-lischke** [comment] 2024-01-11 08:01
Duplicate of #39

**Closed by mike-lischke** 2024-01-11 08:01 UTC
